export type RequestType =
  | "order_dispute"
  | "return_refund"
  | "review_report"
  | "brand_category_request"
  | "package_change"
  | "system_generated";

export type RequestStatus = "pending" | "in_review" | "approved" | "resolved" | "cancelled";
export type RequestPriority = "low" | "medium" | "high" | "urgent";
export type RequesterRole = "user" | "vendor" | "affiliate" | "system";

export interface PlatformRequest {
  id: string;
  type: RequestType;
  status: RequestStatus;
  priority: RequestPriority;
  subject: string;
  description: string;
  requesterName: string;
  requesterRole: RequesterRole;
  requesterEmail: string;
  referenceId?: string; // e.g. order ID, review ID, etc.
  createdAt: string;
  updatedAt: string;
  resolvedAt?: string;
  adminNotes?: string;
  attachments?: string[];
}

export const requestTypeLabels: Record<RequestType, string> = {
  order_dispute: "Order Dispute",
  return_refund: "Return / Refund",
  review_report: "Review Report",
  brand_category_request: "Brand / Category Request",
  package_change: "Package Change",
  system_generated: "System Generated",
};

export const requestTypeDescriptions: Record<RequestType, string> = {
  order_dispute: "Raise a dispute on an order (wrong item, damaged goods, non-delivery)",
  return_refund: "Request a return or refund on an eligible order",
  review_report: "Report abusive or fake reviews for moderation",
  brand_category_request: "Request creation of a new brand or category",
  package_change: "Request to upgrade or downgrade your vendor package",
  system_generated: "Automatically generated by the system",
};

export const statusColors: Record<RequestStatus, string> = {
  pending: "text-yellow-700 bg-yellow-100",
  in_review: "text-blue-700 bg-blue-100",
  approved: "text-green-700 bg-green-100",
  resolved: "text-emerald-700 bg-emerald-100",
  cancelled: "text-red-700 bg-red-100",
};

export const priorityColors: Record<RequestPriority, string> = {
  low: "text-muted-foreground bg-muted",
  medium: "text-blue-700 bg-blue-100",
  high: "text-orange-700 bg-orange-100",
  urgent: "text-red-700 bg-red-100",
};

export const typeIcons: Record<RequestType, string> = {
  order_dispute: "AlertTriangle",
  return_refund: "RotateCcw",
  review_report: "Flag",
  brand_category_request: "FolderPlus",
  package_change: "ArrowUpDown",
  system_generated: "Cpu",
};

export const mockRequests: PlatformRequest[] = [
  {
    id: "REQ-001",
    type: "order_dispute",
    status: "pending",
    priority: "high",
    subject: "Wrong item received — Order #ORD-001",
    description: "I ordered Wireless Headphones but received a different model. The item doesn't match the listing images or description. I need this resolved urgently as I need the correct headphones for work.",
    requesterName: "John Doe",
    requesterRole: "user",
    requesterEmail: "john.doe@email.com",
    referenceId: "ORD-001",
    createdAt: "2024-01-15T10:30:00Z",
    updatedAt: "2024-01-15T10:30:00Z",
  },
  {
    id: "REQ-002",
    type: "return_refund",
    status: "in_review",
    priority: "medium",
    subject: "Refund request for damaged laptop stand",
    description: "The laptop stand arrived with a broken hinge. I've attached photos of the damage. Requesting a full refund as the item is unusable.",
    requesterName: "Jane Smith",
    requesterRole: "user",
    requesterEmail: "jane.smith@email.com",
    referenceId: "ORD-008",
    createdAt: "2024-01-14T14:20:00Z",
    updatedAt: "2024-01-15T09:00:00Z",
    attachments: ["damage_photo_1.jpg", "damage_photo_2.jpg"],
  },
  {
    id: "REQ-003",
    type: "review_report",
    status: "pending",
    priority: "medium",
    subject: "Fake review on Wireless Headphones listing",
    description: "There is a clearly fake 1-star review on my Wireless Headphones product. The reviewer has never purchased this product and the review contains false claims about the product quality.",
    requesterName: "TechHub Store",
    requesterRole: "vendor",
    requesterEmail: "support@techhub.com",
    referenceId: "REV-1245",
    createdAt: "2024-01-14T08:45:00Z",
    updatedAt: "2024-01-14T08:45:00Z",
  },
  {
    id: "REQ-004",
    type: "brand_category_request",
    status: "approved",
    priority: "low",
    subject: "Request to add 'EcoTech' brand",
    description: "I would like to list products under the brand 'EcoTech' which specializes in eco-friendly tech accessories. This brand is not currently available in the system.",
    requesterName: "Fashion Central",
    requesterRole: "vendor",
    requesterEmail: "admin@fashioncentral.com",
    createdAt: "2024-01-13T16:00:00Z",
    updatedAt: "2024-01-14T11:30:00Z",
    adminNotes: "Verified brand legitimacy. Added to brand list.",
  },
  {
    id: "REQ-005",
    type: "package_change",
    status: "pending",
    priority: "medium",
    subject: "Upgrade from Starter to Professional package",
    description: "My product count is nearing the Starter limit. I'd like to upgrade to the Professional package to list more products. Please process this upgrade request.",
    requesterName: "Home Essentials",
    requesterRole: "vendor",
    requesterEmail: "vendor@homeessentials.com",
    referenceId: "PKG-STARTER",
    createdAt: "2024-01-13T12:15:00Z",
    updatedAt: "2024-01-13T12:15:00Z",
  },
  {
    id: "REQ-006",
    type: "system_generated",
    status: "pending",
    priority: "urgent",
    subject: "Order dispute auto-escalated — ORD-005",
    description: "This dispute has been auto-escalated because the vendor did not respond within 48 hours. Original complaint: Customer David Brown reports non-delivery of 6 items from Book Haven totaling $129.99.",
    requesterName: "System",
    requesterRole: "system",
    requesterEmail: "system@vistamart.com",
    referenceId: "ORD-005",
    createdAt: "2024-01-13T00:00:00Z",
    updatedAt: "2024-01-13T00:00:00Z",
  },
  {
    id: "REQ-007",
    type: "order_dispute",
    status: "resolved",
    priority: "high",
    subject: "Non-delivery of order #ORD-003",
    description: "It's been 2 weeks and I still haven't received my order. The tracking shows delivered but nothing arrived at my address.",
    requesterName: "Mike Johnson",
    requesterRole: "user",
    requesterEmail: "mike.j@email.com",
    referenceId: "ORD-003",
    createdAt: "2024-01-10T09:00:00Z",
    updatedAt: "2024-01-12T15:30:00Z",
    resolvedAt: "2024-01-12T15:30:00Z",
    adminNotes: "Confirmed with courier — package delivered to wrong address. Full refund issued.",
  },
  {
    id: "REQ-008",
    type: "return_refund",
    status: "cancelled",
    priority: "low",
    subject: "Return request for phone case",
    description: "I want to return the phone case as I ordered the wrong size.",
    requesterName: "Lisa Garcia",
    requesterRole: "user",
    requesterEmail: "lisa.g@email.com",
    referenceId: "ORD-006",
    createdAt: "2024-01-09T11:20:00Z",
    updatedAt: "2024-01-10T14:00:00Z",
    adminNotes: "Customer withdrew request — kept the item.",
  },
  {
    id: "REQ-009",
    type: "brand_category_request",
    status: "in_review",
    priority: "low",
    subject: "Request new sub-category: 'Smart Home Sensors'",
    description: "I have a growing range of smart home sensor products and would like a dedicated sub-category under Electronics > Smart Home for better discoverability.",
    requesterName: "Sports World",
    requesterRole: "vendor",
    requesterEmail: "vendor@sportsworld.com",
    createdAt: "2024-01-12T10:00:00Z",
    updatedAt: "2024-01-13T08:00:00Z",
  },
  {
    id: "REQ-010",
    type: "order_dispute",
    status: "pending",
    priority: "high",
    subject: "Counterfeit product received — Order #ORD-007",
    description: "The product I received appears to be counterfeit. The packaging and quality are vastly different from what was advertised. I demand a full refund and this vendor should be investigated.",
    requesterName: "Tom Anderson",
    requesterRole: "affiliate",
    requesterEmail: "tom.a@email.com",
    referenceId: "ORD-007",
    createdAt: "2024-01-14T17:00:00Z",
    updatedAt: "2024-01-14T17:00:00Z",
  },
];
